server:
  address: localhost
  port: 8080

spring:
  datasource:
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/daitnu_s2?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
